FROM phasecorex/user-python:3.9

COPY root/ /

ENV PYTHONUNBUFFERED=1

# work is necessary before this can be configurable
ENV BASE_PODCAST_DIR=/data

ARG DEFAULT_ALLOWED_HOST=localhost
ENV ALLOWED_HOSTS=$DEFAULT_ALLOWED_HOST

ARG DEFAULT_DOMAIN=example.com
ENV DOMAIN=$DEFAULT_DOMAIN

ARG DEFAULT_GITBRANCH=master
ENV GITBRANCH=$DEFAULT_GITBRANCH

ARG DEFAULT_ADMIN_USERNAME=admin
ENV ADMIN_USERNAME=$DEFAULT_ADMIN_USERNAME
ARG DEFAULT_ADMIN_PASSWORD=adminadmin
ENV ADMIN_PASSWORD=$DEFAULT_ADMIN_PASSWORD
ARG DEFAULT_ADMIN_EMAIL=admin@example.com
ENV ADMIN_EMAIL=$DEFAULT_ADMIN_EMAIL

CMD ["/app/start-cuddly-potato.sh"]
